spring:
  freemarker:
    cache: false
    suffix: .ftl

logging.level.net.iyiguo.html5.serversentevents: DEBUG


thread.sleep.milliseconds: 2500

cache:
  system_users:
    - id: 1
      name: admin
      pass: null
      role: ADMINISTRATOR
    - id: 2
      name: jack
      pass: null
      role: GUEST
    - id: 3
      name: joe
      pass: null
      role: GUEST
    - id: 4
      name: grace
      pass: null
      role: GUEST

poker-cache:
  rooms:
    - name: Room One
      pass: null
      type: TEST
    - name: Room Two
      pass: null
      type: TEST
  pokers:
    - name: Master
      role: MASTER
    - name: Guest One
      role: GUEST
    - name: Guest Two
      role: GUEST
    - name: Jack
      role: POKER
    - name: Join
      role: POKER